### ISSUE TITLE
Fatal error on make

### ISSUE THREAD

**Issue by IvanAdventure** [leejo/string-crc32#9] opened 2022-02-01 12:35 UTC
With cpan:

% cpan String::CRC32
Reading '/Users/anon/.cpan/Metadata'
  Database was generated on Tue, 01 Feb 2022 10:29:03 GMT
Running install for module 'String::CRC32'
Running make for L/LE/LEEJO/String-CRC32-2.100.tar.gz
Checksum for /Users/anon/.cpan/sources/authors/id/L/LE/LEEJO/String-CRC32-2.100.tar.gz ok

  CPAN.pm: Building L/LE/LEEJO/String-CRC32-2.100.tar.gz

Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for String::CRC32
Writing MYMETA.yml and MYMETA.json
cp CRC32.pod blib/lib/String/CRC32.pod
cp CRC32.pm blib/lib/String/CRC32.pm
Running Mkbootstrap for CRC32 ()
chmod 644 "CRC32.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- CRC32.bs blib/arch/auto/String/CRC32/CRC32.bs 644
"/usr/bin/perl" "/System/Library/Perl/5.18/ExtUtils/xsubpp"  -typemap '/System/Library/Perl/5.18/ExtUtils/typemap' -typemap '/Users/anon/.cpan/build/String-CRC32-2.100-jhYqPQ/typemap'  CRC32.xs > CRC32.xsc
mv CRC32.xsc CRC32.c
cc -c   -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Wno-error=implicit-function-declaration -Os   -DVERSION=\"2.100\" -DXS_VERSION=\"2.100\"  -iwithsysroot "/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"   CRC32.c
rm -f blib/arch/auto/String/CRC32/CRC32.bundle
cc  -bundle -undefined dynamic_lookup -fstack-protector  CRC32.o  -o blib/arch/auto/String/CRC32/CRC32.bundle  \
	      \
	  
chmod 755 blib/arch/auto/String/CRC32/CRC32.bundle
Manifying 1 pod document
  LEEJO/String-CRC32-2.100.tar.gz
  /usr/bin/make -- OK
'YAML' not installed, will not store persistent state
Running make test
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- CRC32.bs blib/arch/auto/String/CRC32/CRC32.bs 644
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/crc.t .. Can't load './blib/arch/auto/String/CRC32/CRC32.bundle' for module String::CRC32: dlopen(./blib/arch/auto/String/CRC32/CRC32.bundle, 2): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs at /System/Library/Perl/5.18/darwin-thread-multi-2level/DynaLoader.pm line 194.
 at t/crc.t line 3.
Compilation failed in require at t/crc.t line 3.
BEGIN failed--compilation aborted at t/crc.t line 3.
t/crc.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 

Test Summary Report
-------------------
t/crc.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.01 cusr  0.01 csys =  0.05 CPU)
Result: FAIL
Failed 1/1 test programs. 0/0 subtests failed.
make: *** [test_dynamic] Error 255
  LEEJO/String-CRC32-2.100.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports LEEJO/String-CRC32-2.100.tar.gz
Running make install
  make test had returned bad status, won't install without force

Or manually I do:
String-CRC32-2.100 % perl Makefile.PL
Generating a Unix-style Makefile
Writing Makefile for String::CRC32
Writing MYMETA.yml and MYMETA.json

String-CRC32-2.100 % make            
Skip blib/lib/String/CRC32.pm (unchanged)
Skip blib/lib/String/CRC32.pod (unchanged)
Running Mkbootstrap for CRC32 ()
chmod 644 "CRC32.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- CRC32.bs blib/arch/auto/String/CRC32/CRC32.bs 644
cc -c   -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -Wno-error=implicit-function-declaration -Os   -DVERSION=\"2.100\" -DXS_VERSION=\"2.100\"  "-I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE"   CRC32.c
CRC32.xs:6:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
make: *** [CRC32.o] Error 1

on MacOs Catalina 10.15.7

Sorry I can't be more help

**Comment by leejo** [comment] 2022-02-01 13:22
Hi, this is a duplicate of #4 - so refer to that.

**Closed as completed by leejo** 2022-02-01 13:22 UTC

**Comment by IvanAdventure** [comment] 2022-02-02 18:54
Thanks for quick response, sorry for wasting your time.

**Comment by leejo** [comment] 2022-02-03 07:59
No worries! Sorry I can't (yet) help with this issue, will try to look into it again soon.
